# Generated by Django 5.1.6 on 2025-04-10 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=1000)),
                ('ouestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Options', to='Code_Mix.questions')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code_Mix.questions')),
            ],
        ),
    ]
