# Generated by Django 5.1.6 on 2025-04-10 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='ouestions',
            new_name='ouestion',
        ),
    ]
