# Generated by Django 5.1.6 on 2025-04-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0002_rename_ouestions_options_ouestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='option',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='category',
        ),
        migrations.AddField(
            model_name='options',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Bronze'), (2, 'Master')], default=1),
        ),
    ]
