# Generated by Django 5.1.6 on 2025-04-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0003_remove_options_option_remove_questions_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='ouestion',
            new_name='Questions',
        ),
    ]
