# Generated by Django 5.1.6 on 2025-04-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0004_rename_ouestion_options_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
