# Generated by Django 5.1.6 on 2025-04-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0005_alter_questions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Bronze'), (2, 'Master')]),
        ),
    ]
