# Generated by Django 5.1.6 on 2025-04-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0006_alter_questions_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='rank',
        ),
        migrations.AddField(
            model_name='questions',
            name='diff_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_category',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('python', 'Python'), ('django', 'Django'), ('isom', 'Isom')], max_length=10, null=True),
        ),
    ]
