# Generated by Django 5.1.6 on 2025-04-22 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0007_remove_questions_rank_questions_diff_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='Questions',
        ),
        migrations.RemoveField(
            model_name='options',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='options',
            name='question_id',
        ),
        migrations.AddField(
            model_name='options',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='options',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Code_Mix.questions'),
        ),
    ]
