# Generated by Django 5.1.6 on 2025-04-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0008_remove_options_questions_remove_options_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='options',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
