# Generated by Django 5.2 on 2025-04-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0010_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation for the correct answer', null=True),
        ),
    ]
