# Generated by Django 5.1.6 on 2025-04-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0011_options_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.AddField(
            model_name='options',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation for the correct answer', null=True),
        ),
    ]
