# Generated by Django 5.1.6 on 2025-04-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0012_fix_explanation_column'),
        ('Code_Mix', '0012_remove_useranswer_user_options_explanation'),
    ]

    operations = [
    ]
