# Generated by Django 5.2 on 2025-04-29 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0013_remove_options_explanation_quizsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_sessions', to='Code_Mix.questions'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
