# Generated by Django 5.2 on 2025-04-30 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0015_useranswer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, help_text='For anonymous users', max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('html', 'HTML'), ('python', 'Python'), ('django', 'Django'), ('isom', 'Isom')], max_length=10, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True)),
                ('current_question_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session_key', 'category', 'difficulty'), ('user', 'category', 'difficulty')},
            },
        ),
    ]
