# Generated by Django 5.1.6 on 2025-04-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0016_quizprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_category',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('python', 'Python'), ('django', 'Django')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='category',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('python', 'Python'), ('django', 'Django')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='category',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('python', 'Python'), ('django', 'Django')], max_length=10, null=True),
        ),
    ]
