# Generated by Django 5.2 on 2025-04-30 16:51

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    """
    Create initial categories and difficulty levels
    """
    QuizCategory = apps.get_model('Code_Mix', 'QuizCategory')
    QuizDifficulty = apps.get_model('Code_Mix', 'QuizDifficulty')
    
    categories = [
        {'name': 'html', 'display_name': 'HTML'},
        {'name': 'python', 'display_name': 'Python'},
        {'name': 'django', 'display_name': 'Django'},
        {'name': 'isom', 'display_name': 'ISOM'},
    ]
    
    for category_data in categories:
        QuizCategory.objects.create(**category_data)
    
    difficulties = [
        {'level': 'easy', 'display_name': 'Easy'},
        {'level': 'medium', 'display_name': 'Medium'},
        {'level': 'hard', 'display_name': 'Hard'},
    ]
    
    for difficulty_data in difficulties:
        QuizDifficulty.objects.create(**difficulty_data)


def reverse_initial_categories(apps, schema_editor):
    """
    Remove initial categories and difficulty levels
    """
    QuizCategory = apps.get_model('Code_Mix', 'QuizCategory')
    QuizDifficulty = apps.get_model('Code_Mix', 'QuizDifficulty')
    
    QuizCategory.objects.all().delete()
    QuizDifficulty.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0016_add_quiz_categories'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, reverse_initial_categories),
    ]
