# Generated by Django 5.1.6 on 2025-04-30 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0017_alter_questions_question_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('html', 'HTML'), ('python', 'Python'), ('django', 'Django'), ('isom', 'Isom')], max_length=10, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Quiz Categories',
            },
        ),
        migrations.CreateModel(
            name='QuizDifficulty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Quiz Difficulty Levels',
            },
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['quiz_category', 'quiz_difficulty', 'question_number'], 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizprogress',
            options={'verbose_name_plural': 'Quiz Progress'},
        ),
        migrations.AddField(
            model_name='questions',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, help_text='Question number within this category and difficulty (e.g., q1, q2, q3)', null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_category',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('python', 'Python'), ('django', 'Django'), ('isom', 'Isom')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='category',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('python', 'Python'), ('django', 'Django'), ('isom', 'Isom')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='category',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('python', 'Python'), ('django', 'Django'), ('isom', 'Isom')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='Code_Mix.quizcategory'),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='quiz_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_progress', to='Code_Mix.quizcategory'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='quiz_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answers', to='Code_Mix.quizcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='quizprogress',
            unique_together={('session_key', 'category', 'difficulty'), ('user', 'category', 'difficulty')},
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz_difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='Code_Mix.quizdifficulty'),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='quiz_difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_progress', to='Code_Mix.quizdifficulty'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='quiz_difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answers', to='Code_Mix.quizdifficulty'),
        ),
        migrations.AlterUniqueTogether(
            name='quizprogress',
            unique_together={('session_key', 'category', 'difficulty'), ('session_key', 'quiz_category', 'quiz_difficulty'), ('user', 'category', 'difficulty'), ('user', 'quiz_category', 'quiz_difficulty')},
        ),
    ]
