# Generated by Django 5.1.6 on 2025-04-30 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0018_quizcategory_quizdifficulty_alter_questions_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='quiz_category',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='quiz_category',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='quiz_difficulty',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='quiz_difficulty',
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizprogress',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='quizprogress',
            unique_together={('session_key', 'category', 'difficulty'), ('user', 'category', 'difficulty')},
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_number',
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_category',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('python', 'Python'), ('django', 'Django')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='category',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('python', 'Python'), ('django', 'Django')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='category',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('python', 'Python'), ('django', 'Django')], max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='quizprogress',
            name='quiz_category',
        ),
        migrations.RemoveField(
            model_name='quizprogress',
            name='quiz_difficulty',
        ),
        migrations.DeleteModel(
            name='QuizCategory',
        ),
        migrations.DeleteModel(
            name='QuizDifficulty',
        ),
    ]
