# Generated by Django 5.1.6 on 2025-05-13 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0019_remove_questions_quiz_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='quizprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='questions',
            name='answered_by',
            field=models.ManyToManyField(blank=True, related_name='answered_questions', through='Code_Mix.UserAnswer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='options',
            name='answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='options',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='options',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='options',
            name='option_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='options',
            name='option_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='options',
            name='option_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='options',
            name='option_4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='options',
            name='question',
            field=models.OneToOneField(blank=True, help_text='Question for which this option is valid', null=True, on_delete=django.db.models.deletion.CASCADE, to='Code_Mix.questions'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='current_question_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='difficulty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='difficulty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code_Mix.questions'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_category', models.CharField(blank=True, choices=[('html', 'HTML'), ('python', 'Python'), ('django', 'Django')], help_text='Category the user is currently working on', max_length=10, null=True)),
                ('current_difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Difficulty level the user is currently working on', max_length=10, null=True)),
                ('categories_started', models.JSONField(blank=True, default=list, help_text='List of categories the user has started')),
                ('categories_finished', models.JSONField(blank=True, default=list, help_text='List of categories the user has completed')),
                ('total_answered', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_wrong', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
