# Generated by Django 5.1.6 on 2025-05-23 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Mix', '0021_user_options_title_q'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserData',
        ),
    ]
